### ISSUE TITLE
No such file or directory: './SecretCode.txt'

### ISSUE THREAD

**Issue by bibkia** [theriley106/WaltonAnalytics#2]
PS C:\Users\XXXXX\Dollar_Drop> python app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    import Analytics
  File "C:\Users\XXXXX\Dollar_Drop\Analytics.py", line 14, in <module>
    r = requests.post("http://138.197.123.15:8888/proxies/{}".format(open('./SecretCode.txt').read().strip())).json()
IOError: [Errno 2] No such file or directory: './SecretCode.txt'

**Comment by Aeowon** [comment]
Also having this issue. Fix?

**Comment by theriley106** [comment]
Sorry about this - not sure why I added that in.  I used to have a VPS running that would scrape proxies to use with this program, and I honestly didn't think Walton Analytics would actually have users lol.

I fixed that error and everything should work properly now.  Thanks for letting me @Aeowon and @bibkia
